#####################
# Exclusion/Inclusion

AllCops:
  Exclude:
    - '.git/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
  RSpec:
    Patterns:
    - _spec.rb
    - "(?:^|/)spec/"
  RSpec/FactoryBot:
    Patterns:
    - spec/factories/**/*.rb
    - features/support/factories/**/*.rb

inherit_from:
  - './rubocop-bundler.yml'
  - './rubocop-gemspec.yml'
  - './rubocop-layout.yml'
  - './rubocop-lint.yml'
  - './rubocop-metrics.yml'
  - './rubocop-naming.yml'
  - './rubocop-performance.yml'
  - './rubocop-rails.yml'
  - './rubocop-rspec.yml'
  - './rubocop-security.yml'
  - './rubocop-style.yml'
